'use strict';
module.exports={modules:['persona/alias-registry.js','persona/knowledge-path.js','app/pages/helpdesk.js'],run:function(ctx,assert){
    var t=ctx.helpDeskCreateTicket({subject:'Runtime offline',description:'Health endpoint unavailable',requester:'Operator',category:'RUNTIME',priority:'CRITICAL'},[],new Date('2026-01-01T00:00:00Z'));
    assert(t.id==='HD-0001','first ticket receives deterministic ID');
    assert(t.assignee==='@VICTOR','runtime ticket routes to @VICTOR');
    assert(t.dueAt==='2026-01-01T04:00:00.000Z','critical ticket receives four-hour SLA');
    assert(ctx.helpDeskSlaState(t,new Date('2026-01-01T05:00:00Z'))==='BREACHED','open overdue ticket breaches SLA');
    var result=ctx.helpDeskTransition(t,'RESOLVED','@VICTOR','Service restored',new Date('2026-01-01T02:00:00Z'));
    assert(result.ok&&t.status==='RESOLVED'&&!!t.resolvedAt,'valid transition resolves ticket');
    assert(ctx.helpDeskSlaState(t,new Date('2026-01-02T00:00:00Z'))==='COMPLETE','resolved ticket reports complete SLA');
    assert(t.history.length===2&&t.history[1].action==='STATUS_CHANGED','status transition appends history');
    assert(ctx.helpDeskTransition(t,'INVALID','x','x').error==='INVALID_STATUS','invalid status is rejected');
    assert(ctx.helpDeskNextId([{id:'HD-0009'},{id:'legacy'}])==='HD-0010','ticket IDs advance without collision');
    var members=[{serviceMemberId:'ATA-ONE-000',callsign:'@ONE',memberProfile:{toolProfile:{assignedTools:['CRM','Email']}}},{serviceMemberId:'ATA-TWO-000',callsign:'@TWO',memberProfile:{toolProfile:{assignedTools:['CRM','Runtime logs']}}}];
    var registry=ctx.helpDeskToolRegistry(members);
    assert(registry.uniqueTools===3&&registry.assignments===4,'tool registry deduplicates tools while retaining assignments');
    var generated=ctx.buildToolReadinessTickets(members,[],new Date('2026-01-01T00:00:00Z'));
    assert(generated.created.length===2&&generated.created[0].toolInventory.total===2,'tool extrapolation creates one complete readiness ticket per identity');
    assert(generated.created[0].assignee==='@ONE'&&generated.created[1].assignee==='@TWO','tool tickets remain owned by their canonical identities');
    var rerun=ctx.buildToolReadinessTickets(members,generated.created,new Date('2026-01-01T00:00:00Z'));
    assert(rerun.created.length===0&&rerun.skipped.length===2,'tool ticket generation is idempotent and creates no duplicates');
    var pilotMembers=[{serviceMemberId:'ATA-CINDY-000',callsign:'@CINDY'},{serviceMemberId:'ATA-VICTOR-000',callsign:'@VICTOR'},{serviceMemberId:'ATA-HELIX-000',callsign:'@HELIX'}];
    ctx.DATA={participants:pilotMembers}; // recordKnowledgePathStageEvidence resolves the verifier against real identities
    var pilot=ctx.buildKnowledgePathPilotTickets(pilotMembers,[],new Date('2026-01-01T00:00:00Z'));
    assert(pilot.created.length===2&&pilot.errors.length===0,'knowledge-path pilot creates exactly two learner tickets');
    assert(pilot.created.every(function(x){return x.status==='OPEN'&&x.knowledgePathPilot.stageId==='competencies'&&x.knowledgePathPilot.state==='EVIDENCE_REQUIRED';}),'pilot tickets collect Competency Baseline evidence without verifying a stage');
    assert(pilot.created[0].knowledgePathPilot.reviewer==='@HELIX'&&pilot.created[1].knowledgePathPilot.reviewer==='@HELIX','@HELIX is retained as independent reviewer, not learner owner');
    var pilotAgain=ctx.buildKnowledgePathPilotTickets(pilotMembers,pilot.created,new Date('2026-01-01T00:00:00Z'));
    assert(pilotAgain.created.length===0&&pilotAgain.skipped.length===2,'knowledge-path pilot ticket generation is idempotent');
    var pt=pilot.created[0],learner={serviceMemberId:'ATA-CINDY-000',knowledgePath:ctx.buildDefaultKnowledgePath()};
    var incomplete=ctx.submitKnowledgePathPilotEvidence(pt,{standardVersion:'v1'});
    assert(!incomplete.ok&&incomplete.error==='MISSING_REQUIRED_EVIDENCE','pilot submission rejects incomplete evidence packages');
    var evidence={standardVersion:'STD-v1',sourceReference:'SRC-1',audienceRole:'Customer Service Operations',trainingMethod:'Controlled workshop',completionArtifact:'ART-1',completedAt:'2026-01-01T01:00',assessmentResult:'PASS 90%',exceptions:'NONE',evidenceReference:'EVID-1',submittedBy:'@CINDY'};
    var submitted=ctx.submitKnowledgePathPilotEvidence(pt,evidence,new Date('2026-01-01T02:00:00Z'));
    assert(submitted.ok&&pt.knowledgePathPilot.state==='REVIEW_REQUIRED'&&pt.status==='WAITING'&&pt.assignee==='@HELIX','complete evidence submits to @HELIX without verifying the stage');
    assert(learner.knowledgePath.stages[0].status==='PENDING','submission alone leaves Competency Baseline PENDING');
    var wrongReviewer=ctx.reviewKnowledgePathPilotEvidence(pt,'APPROVE','@CINDY','looks good',learner,new Date('2026-01-01T03:00:00Z'));
    assert(!wrongReviewer.ok&&wrongReviewer.error==='REVIEWER_MISMATCH','learner cannot approve their own pilot evidence');
    var rejected=ctx.reviewKnowledgePathPilotEvidence(pt,'REJECT','@HELIX','Attach source page',learner,new Date('2026-01-01T03:00:00Z'));
    assert(rejected.ok&&!rejected.verified&&pt.knowledgePathPilot.state==='CORRECTION_REQUIRED'&&learner.knowledgePath.stages[0].status==='PENDING','rejection returns evidence for correction and preserves PENDING stage');
    ctx.submitKnowledgePathPilotEvidence(pt,evidence,new Date('2026-01-01T04:00:00Z'));
    var approved=ctx.reviewKnowledgePathPilotEvidence(pt,'APPROVE','@HELIX','Evidence complete',learner,new Date('2026-01-01T05:00:00Z'));
    assert(approved.ok&&approved.verified&&pt.status==='RESOLVED','@HELIX approval resolves the pilot ticket');
    assert(learner.knowledgePath.stages[0].status==='VERIFIED'&&learner.knowledgePath.stages[0].verifier==='ATA-HELIX-000','approved complete evidence verifies only the targeted Competency Baseline stage, storing the resolved canonical verifier ID');

    // Tool Readiness: real linkage to the Knowledge Path 'tools' stage, mirroring the pilot.
    var toolSubject={serviceMemberId:'ATA-ONE-000',callsign:'@ONE',memberProfile:{toolProfile:{assignedTools:['CRM','Email']}},knowledgePath:ctx.buildDefaultKnowledgePath()};
    ctx.DATA={participants:[toolSubject,{serviceMemberId:'ATA-HELIX-000',callsign:'@HELIX'}]};
    var toolTickets=ctx.buildToolReadinessTickets([toolSubject],[],new Date('2026-01-01T00:00:00Z'));
    assert(toolTickets.created.length===1,'one Tool Readiness ticket is created for the one identity with assigned tools');
    var tt=toolTickets.created[0];
    assert(tt.toolReadinessReview&&tt.toolReadinessReview.stageId==='tools'&&tt.toolReadinessReview.reviewer==='@HELIX'&&tt.toolReadinessReview.state==='EVIDENCE_REQUIRED','the ticket carries a real, HELIX-reviewed link to the Knowledge Path tools stage, not just inventory data');
    var emptyEvidence=ctx.submitToolReadinessEvidence(tt,'   ');
    assert(!emptyEvidence.ok&&emptyEvidence.error==='MISSING_REQUIRED_EVIDENCE','blank evidence is rejected, not silently accepted');
    var trSubmitted=ctx.submitToolReadinessEvidence(tt,'CRM connection confirmed, least-privilege scoped, negative test passed.','2026-01-01T01:00:00Z');
    assert(trSubmitted.ok&&tt.toolReadinessReview.state==='REVIEW_REQUIRED'&&tt.status==='WAITING'&&tt.assignee==='@HELIX','evidence submission moves to review without verifying the stage');
    assert(toolSubject.knowledgePath.stages.find(function(s){return s.id==='tools';}).status==='PENDING','submission alone leaves Tool Enablement PENDING');
    var trWrongReviewer=ctx.reviewToolReadinessEvidence(tt,'APPROVE','@ONE','looks fine',toolSubject,new Date('2026-01-01T02:00:00Z'));
    assert(!trWrongReviewer.ok&&trWrongReviewer.error==='REVIEWER_MISMATCH','the subject cannot approve their own tool-readiness evidence');
    var trNoNote=ctx.reviewToolReadinessEvidence(tt,'APPROVE','@HELIX','',toolSubject,new Date('2026-01-01T03:00:00Z'));
    assert(!trNoNote.ok&&trNoNote.error==='REVIEW_NOTE_REQUIRED','a review with no note is rejected regardless of decision');
    var trReallyApproved=ctx.reviewToolReadinessEvidence(tt,'APPROVE','@HELIX','Confirmed and tested',toolSubject,new Date('2026-01-01T03:00:00Z'));
    assert(trReallyApproved.ok&&trReallyApproved.verified&&tt.status==='RESOLVED','HELIX approval resolves the ticket and verifies the stage');
    var toolsStage=toolSubject.knowledgePath.stages.find(function(s){return s.id==='tools';});
    assert(toolsStage.status==='VERIFIED'&&toolsStage.verifier==='ATA-HELIX-000','approved tool-readiness evidence verifies the real Tool Enablement stage with the resolved canonical verifier ID');
    assert(tt.toolInventory.status==='VERIFIED','the ticket'+"'"+'s own tool inventory summary reflects the real verified outcome, not left at REVIEW_REQUIRED');
}};
